# Generated by Django 3.2.20 on 2024-04-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
