# Generated by Django 3.2.20 on 2024-07-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocklist', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Threshold',
        ),
    ]
